-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 15 Nov 2017 pada 02.53
-- Versi Server: 10.1.16-MariaDB
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zodiak`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `ramal`
--

CREATE TABLE `ramal` (
  `nama_zodiak` varchar(20) NOT NULL,
  `tanggal` varchar(30) NOT NULL,
  `ramalan` text NOT NULL,
  `karakter` text NOT NULL,
  `kesehatan` text NOT NULL,
  `angka_keberuntungan` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `ramal`
--

INSERT INTO `ramal` (`nama_zodiak`, `tanggal`, `ramalan`, `karakter`, `kesehatan`, `angka_keberuntungan`) VALUES
('Aquarius', '21 Januari - 19 Februari', 'Kaum Aquarius tertarik pada pasangan yang memiliki kepandaian. Mereka senang mencoba termasuk mencoba hal baru dalam hal percintaan dan romantisme. Kaum Aquarius kadnag bersikap dingin dan acuh namun dibalik semuanya itu dia sangat pasangan yang penuh kasih yang selalu mencoba hal baru dan lain dari yang biasanya.', 'Berbudi luhur, selalu memperjuangkan keadilan, kemajuan, dan kesejahteraan. Bersedia berkorban untuk kebahagiaan orang lain. Ada yang berwatak keras kepala terkadang suka melamun. Berbakat dalam menciptakan karya-karya baru dalam hal musik. Cerdas, namun karena suka melamun kadang-kadang menjadi tidak menentu. Keseimbangan dalam jiwanya amat tinggi banyak orang yang meminta nasehat kepadanya. Manis peramah, suka pada kehiudupan yang lurus. Hemat, tidak tamak terhadap kebendaan. Wanita Aquarius tidak segan, berani bertindak melebihi kaum pria. Kelemahannya, suka menunda-nunda pekerjaan, seringkali sombong, gila hormat, bicaranya seringkali berlebihan sehingga seringkali menimnulkan kedustaan dalam membanggakan diri. Kadang kala kehilangan kepercayaan diri. Bila hendak mencapai maksudnya, kadang sampai hati melanggar aturan.', 'Mudah terserang penyakit tulang, saraf, peredaran darah kurang lancar, sakit kepala, sakit otak. Sebaiknya jangan terlalu banyak bekerja dengan otak. Atur keseimbangan antara bekerja dan beristirahat.', 14),
('Aries', '21 Maret – 19 April', 'Hal ini terlihat jelas apabila para Aries sedang jatuh cinta. Mereka akan mengejar apa yang mereka inginkan sampai dapat. Apabila ini terjadi pada kalian, berhati-hatilah. Aries tidak pernah mau menerima jawaban tidak. Sayangnya, jika kamu tidak bisa mengikuti jalan hidupnya, mereka akan meninggalkanmu dan berpindah ke lain hati.', 'Ulet, pekerja keras, tabah, tak mudah putus asa, suka berkorban, semangatnya tinggi, dan tidak suka bermalas-malasan. Sanggup menghadapi segala rintangan. Berhati besar, tidak suka berbohong. Gemar pada kesenian dan keindahan. Berbakat untuk memiliki kekuatan gaib. Kelemahannya, suka berubah pikiran hingga sering salah perhitungan, selalu tidak puas, mudah tersinggung, pemarah, suka menyerang (agresif).', 'Kadang-kadang dapat terserang penyakit kepala yang ada hubungannya dengan penyakit mata dan hidung. Pikirannya sangat kuat, dan karenanya ia dapat menyembuhkan penyakitnya. Ia dapat pula diserang oleh penyakit yang hebat, namun dengan cara yang aneh dapat sembuh sendiri.', 11),
('Cancer', '22 Juni - Juli 22', 'Zodiak ini tertarik pada kecantikan, namun demikian mereka juga mendambakan kecerdasan didalam kecantikan, karena mereka menawarkan kasih sayang, kesetiaan, dan pesona intelektualitas, mereka menyukai pasangan yang memiliki kriteria tersebut. Bila mereka telah jatuh hati padamu, mereka tidak akan pernah melepaskanmu. Mereka senantiasa melindungimu dan selalu memberikan rasa aman dan nyaman. Mereka akan selalu melakukan apapun bagi pasangannya.', 'Gemar kepada kekuatan gaib, kebatinan, gerakannya agak lambat, pandai bergaul, dan sangat teliti. Kelemahannya, suka berhayal, pemalu, hatinya lembek, dan mudah tersinggung.', 'Dapat terserang gangguan pencernaan. Oleh karena itu hindari makanan pedas atau makanan yang dingin (es).\r\n\r\n ', 23),
('Capricorn', '22 Desember - 20 Januari', 'Cenderung sexy dan teguh dalam hal percintaan dan hubungan. Mereka tidak terima jawaban tidak. Jadi, jika kamu menjadi sasaran cintanya, berhati-hatilah. Mereka akan menyeretmu kehadapannya dengan kekuatan dan pesonanya. Cinta adalah suatu kebutuhan bagi zodiak ini dan begitu mereka mendapatkannya, mereka akan memperlakukannya bagaikan barang berharga. Capricorn sangat setia selama pasangannya selalu bersedia membantunya.', 'Senang berpura-pura segan, namun sebenarnya ingin menonjol. Suka menyendiri, kadang-kadang ragu-ragu dan curiga. Akan tetapi bila keputusannya sudah diambil pendiriannya kuat. Senang dipuji sesuai dengan kecakapannya. Berani bertanggung jawab, ulet dan pandai dalam perhitungan untung rugi. Cendrung kepada kekolotan dan suka pada tradisi. Hemat dan sedikit pelit, namum suka menolong orang yang perlu ditolong. Ulet dalam bekerja. Kelemahannya, pemarah, mudah tersinggung, biasanya memikirkan kesulitan secara mendalam. Sukar memaafkan orang yang telah ingkar janji.', 'Sewaktu anak-anak sampai berumur 7 tahun kesehatannya kurang baik, sering sakit-sakitan, biasanya terkena pilek, batuk, perut kembung. Namun seiring dengan bertambahnya umur kesehatannya semakin membaik. Oleh karena itu, kesehatannya perlu diperhatikan sampai mencapai umur dewasa. Apabila masa sakit-sakitan telah dilewati maka selanjutnya akan tahan dengan berbagai macam penyakit sehingga dapat mencapai umur panjang.', 19),
('Gemini', '21 Mei - Juni 21', 'Jika kamu tidak dapat mengikuti pola pikir para Gemini, kamu tidak akan dapat bergaul dengan zodiak ini. Perubahan sikap adalah kunci memenangkan hati mereka. Gemini akan menggunakan kemampuan berkomunikasi mereka untuk merayu orang yang mereka sukai. Mereka cenderung menjauh dari orang yang tidak menantang mereka. Gemini memiliki rasa ingin tahu yang tinggi dan selama kamu dapat menimbulkan keingintahuan di hati mereka, mereka selamanya akan berada di sampingmu. Gemini menukai perubahan, mereka senantiasa mencari sesuatu yang lain, termasuk juga kekasih.', 'Cerdas, pirasatnya tajam, berbakat menjadi orang pintar. Sopan santun dan disukai oleh setiap orang. Hatinya terbuka, suka menolong orang lain sekalipun dengan meminjam, suka pada pelajaran tinggi, dan pandai berbicara. Kelemahannya, Susah dapat menyimpan uang karena suka menghabiskan uangnya untuk menolong orang lain. Suka memerintah, tetapi akhirnya mundur teratur. Pemberani, tetapi pada lain waktu penakut, dan mudah tersinggung.', 'Mudah terserang penyakit saraf, sering sakit kepala sampai tidak bisa tidur. Mudah lelah baik badan maupun jiwa. Sedapat mungkin jangan menggunakan pengobatan listrik. Paad umur 42 sebaiknya berhati-hati karena mudah terserang berbagai penyakit. Waktu kanak-kanak mudah cacingan. Harus banyak istirahat, jangan terlalu banyak bekerja dengan otak. Perlu latihan pernafasan untuk mencegah penyakit paru-paru. Harus diperlakukan dengan sabar, tidak boleh dimaki-maki dengan kata-kata kasar karena perasaanya halus. Antara umur 14 - 20tahun pertumbuhannya baik asal kesehatannya dijaga.\r\n\r\n ', 26),
('Leo', '23 Juli - 23 Agustus', 'Leo selalu membanggakan dirinya sebagai pecinta yang hangat. Prilaku mereka nampak dengan sikapnya yang sombong dan sok kuasa tetapi sifat inilah yang membuat mereka menjadi sangat terkenal di dalam hal bercinta. Mereka tidak suka pasangan yang melebihi dirinya. Leo cenderung dermawan, pandai beradaptasi dan penuh perhatian. Mereka selalu menyenangkan pasangannya sehingga pasangannya selalu senang berada di dekatnya. Leo juga mudah cemburu bila pasangannya lebih memperhatikan orang lain daripada dirinya.', 'Angker dan agung, tegap perawakannya, pundaknya lebar, langkah kakinya kuat, mukanya berseri-seri, matanya bersinar, postur seluruh tubuhnya serba berimbang. Jujur dan setia, ramah-tamah, suka kepada kemewahan. Suka berkeja dengan sungguh-sungguh dan tidak tanggung-tanggung, mau menerima kecaman yang berdasar kebenaran, dan suka memaafkan. Kelemahannya, tidak mau di bawah perintah orang lain, kalau mencintai sering membuta tuli. Bilamana kurang pendidikan, sikap agungnya berubah menjai sombong dan dusta. Rakus terhadap makanan, mudah tertarik kepada lawan jenis, suka memandang remeh orang lain. Wanita Leo lebih boros dari pria.', 'Peka terhadap penyakit jantung, paru-paru, dan kurang darah. Bila sakit perlu banyak hiburan.', 26),
('Libra', '23 September - 23 Oktober', 'Para Libra akan mengerjakan apa saja demi memuaskan pasangannya. Mereka tertarik pada individual yang cantik/tampan. Para Libra tidak suka kata-kata kotor, penampilan yang sembrono atau prilaku buruk dari pasangannya. Para Libra tidak suka menyakiti orang lain. Keagungan, kemurahan hatinya dan pesonanya akan selalu menarik orang di dekatnya. Rasa aman yang didapatnya akan membuatnya bahagia.', 'Parasnya bundar, namun ada pula yang lonjong, suaranya nyaring, sorot matanya bagus terutama kaum wanitanya. Ada dua macam orang Libra, Pertama riang gembira, namun tiba-tiba sedih, dan yang kedua selalu sedih namun mendadak menjai riang gembira. Suka kepada kemewahan, suka damai. Baik pria maupun wanita, Libra suka kepada keserasian dan senantiasa menjauhi permusuhan. Budi bahasanya manis, senyumnya menarik. Firasatnya tajam, seringkali dugaannya tepat. Kelamahannya, pelit saking hematnya, pemalu, tidak mudah melupakan kesalahan orang kepadanya. Sukar untuk dicintai karena perkataannya suka menyinggung perasaan orang lain dan ia tidak peduli dicintai atau tidak. Kalau niatnya dirintangi ia bisa mengamuk dan menuntut balas. Malas bekerja seniri. Nafsu birahinya tinggi. Tidak suka dicela, dan tidak sabar.', 'Dapat terserang penyakit ginjal, kulit, maag, ekseem, dan bagi wanita bermasalah dengan datang bulan (tidak tepat), Waktu kecil kebanyakan kurus, namun bila sudah besar dapat menjadi gemuk.', 22),
('Pisces', '20 Februari - 20 Maret', 'Pisces cenderung menjadi pasangan yang penuh gairah, peduli pada kebutuhan pasangannya dan ingin menyenangkan pasangannya. Mereka ahli membuat situasi menjadi terbalik dan mudah memanipulasi pasangannya. Kaum pisces paling sulit dimengerti, terutama bila itu menyangkut urusan percintaan. Mereka sering melakukan sesuatu yang berlawanan dengan perkataan mereka. Mereka perayu yang hebat dan penuh ide-ide baru yang sulit untuk ditolak dan dilupakan.', 'Orang Pisces umumnya mempunyai watak campuran baik dan buruk kelemahannya bersama-sama dengan kekuatannya. Mempunyai sifat perwira. Bila terlepas dari ketetapan hatinya, sering timbul kebimbangan. Mudah terpengaruh oleh lingkungan dan pergaulan. Suka dengan pemandangan alam, suka merantau. Pandai berbicara dan seringkali mengalahkan lawan bicaranya dalam berdebat. Suka menolong orang yang menderita, kadang kala dengan uang yang berlebihan, sehingga sering menimbulkan penyesalan kemudian. Pemahaman keagamannya amat mendalam sehingga dapat menjadi pemimpin agama atau organisasi keagamaan. Kelemahannya, pemarah, pemalu, pelupa, dan kadang keras kepala.', 'Pada masa kanak-kanak kesehatannya kurang baik, namun seiring dengan bertambahnya umur kesehatannya membaik. Mudah terserang penyakit paru dan penyakit kaki. Disarankan jangan menggunakan obat-obatan yang dapat mematikan rasa dan jauhkan dari alkohol dan narkoba. Pada umur 14-21 tahun harus diperhatikan dan dijaga paru-parunya.', 13),
('Sagittarius', '23 November - 21 Desember', 'Sagitarius tidak suka komitmen, mereka takut terikat dan kehilangan kebebasannya. Mereka menjalin hubungan yang memungkinkan mereka untuk datang dan pergi sesuka hatinya. Namun bila mereka menemukan pasangan yang setuju dengan gaya hidupnya, mereka akan menghabiskan waktu bersama pasangannya selamanya. Sagitarius suka mencoba hal baru, demikian juga dalam hal bercinta. Mereka gemar mencoba dan akan cepat bosan bila bercinta di tempat yang sama.', 'Berbudi luhur, senantiasa memikirkan cara-cara menaikkan martabat manusia dan kemakmuran masyarakat. Budi bahasanya manis, peramah, dan oleh karenanya banyak disukai orang. Berani berkorban untuk orang lain. Sanggup bekerja keras, berhati-hati, dan disiplin sehingga sering mendapatkan keudukan tinggi di masyarakat. Orang sagitarius mungkin menyeniri untuk menempuh hidup suci. Wanita sagitarius pandai mengatur rumah tangga, dicintai oleh keluarganya karena adil, namun keras. Kelemahannya, bangga akan kepandaiannya sendiri, suka mengejek dengan cara terbungkus yang menginggung orang lain. Orang sagitarius yang kurang pendidikan, suka marah, merusak, mau menang sendiri, berbuat nekat. Dalam memberikan pertolongan kepada orang sering melewati batas, dan sering kebaikan, kejujuran dan kedermawanannya disia-siakan orang.', 'Mudah terserang penyakit rematik, paru-paru, patah tulang kaki, asma, batuk, dan bronchitis.', 25),
('Scorpio', '24 Oktober - 22 November', 'Scorpio adalah zodiak yang paling perasa. Mereka penuh gairah, setia dan sangat romantis. Mereka tidak akan terlibat dalam suatu hubungan tanpa penyelidikan terlebih dahulu untuk mengetahui apakah pilihannya itu merupakan pribadi yang setia dan jujur. Bila iya, maka ia akan menunjukkan sisi pribadi yang selama ini dia sembunyikan. Mereka sangat pencemburu jika menemukan sesuatu yang dicurigai tanpa alasan yang kuat. Tidak ada yang dapat menyakiti Scorpio kecuali perasaan dicurangi dan dikhianati oleh pasangannya.', 'Pejuang yang jujur hingga berani memberontak, tidak suka diperintah orang lain, terlalu pegang pada janji, berbakat besar tentang ilmu gaib, pandangannya luas, mudah belajar bahasa asing. Suka berpakaian bagus, rumah baik, dan rapi. Pandai menyimpan rahasia dan karenanya mudah dipercaya. Tajam dan berbakat pada ilmu watak manusia. Kelemahannya, kalau sedang sedih tidak banyak bicara dan perkataanya sering menyakiti hati orang lain. Suka mengumbar nafsu, dapat berbuat kejam, senang dipuji, kalau keinginannya tidak tercapai dapat berbuat nekat. Cemburu, tidak suka dikecam dan dibantah.', 'Mudah terserang penyakit kelamin, jantung, sakit pinggang, batu ginjal, hidung (polip). Wanitanya dapat terserang keputihan dan bagian peranakannya.', 27),
('Taurus', '21 April - Mei 20', 'Para Taurus cenderung pendiam dan bergairah. Mereka berusaha untuk memberikan yang terbaik dalam hidup mereka seperti musik yang lembut, lampu yang redup, dan anggur terbaik untuk menemani mereka menghabiskan waktunya dengan orang yang mereka cintai. Taurus selalu mengutarakan hatinya secara langsung dan tidak suka bertele-tele bila menyangkut urusan cinta. Mereka berusaha menyenangkan hatimu dengan harapan mendapatkan balasan yang sama dari pasangannya.', 'Umumnya sangat setia kepada sahabat-sahabatnya dan sanggup membela secara gigih, berani dan bertanggung jawab. Sabar, namun bila marah membahayakan. Tidak suka pada hal yang kecil dan sepele. Suka membangun sesuatu yang diharapkan akan kekal. Perasaannya halus sehingga dapat merasakan kesulitan orang lain dan selalu ingin menolong. Firasatnya tajam dan cepat mengetahui sifat orang yang dihadapinya. Pada umumnya bekerja lamban, tetapi kalau sudah mau bekerja, ia akan bekerja keras dan kadang-kadang sampai di luar kekuatannya. Kelemahannya, perlente, suka berpakaian bagus sampai hari tua. Cepat menarik dan ditarik oleh lawan jenis. Kalau marah sering merusak.', 'Mudah terserang penyakit tenggorokan dan penyakit kelamin. Nafsu birahinya tinggi, dan karena itu perlu berhati-hati dengan penyakit kelamin.\r\n\r\n ', 12),
('Virgo', '24 Agustus - 22 September', 'Para virgo senang menjalin kasih dengan orang yang dianggapnya membawa banyak keuntungan bagi dirinya. Mereka perlu jaminan dari pasangannya bahwa pasangannya akan bekerja sama giatnya dengan virgo. Mereka memiliki rasa ingin tahu yang besar menyangkut cinta dan sex, dan selalu bereksperimen sebelum membuat ikatan. Sebelum menentukan pasangan, virgo harus yakin betul bahwa pasangannya dapat memenuhi segala kebutuhannya secara profesional. Dia lebih suka hidup sendiri daripada tinggal dengan orang yang tidak sesuai dengan hatinya.', 'Otaknya cemerlang, mudah memahami pelajaran, setia pada keluarga, sopan santun, suka berpakaian rapi dan bagus. Suka mengalah, tidak mudah memutuskan hubungan. Riang gembira, mukanya berseri-seri, awet muda, dan suka pada anak-anak. Kelemahannya, bilamana kurang pendidikan dapat berbuat sewenang-wenang, sombong akan kekayaan dan kedudukanya. Suka merusak barang-barang bila marah. Tidak mau mengaku salah, suka berhutang, tidak dapat dipercaya. Tetapi kalau berpendidikan baik, orang Virgo paling mudah dipercaya.\r\n\r\n ', 'Mudah terserang penyakit perut, limpa, cacing pita, kolera, usus buntu, disentri, dan sesak nafas. Namun mempunyai keajaiban untuk menyembuhkan diri sendiri.', 25);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ramal`
--
ALTER TABLE `ramal`
  ADD UNIQUE KEY `nama_zodiak` (`nama_zodiak`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
